If a trcli run fails, continue further uploads, and do not fail the GHA.

diff --git a/.github/workflows/cypress.yaml b/.github/workflows/cypress.yaml
--- a/.github/workflows/cypress.yaml
+++ b/.github/workflows/cypress.yaml
@@ -230,7 +230,7 @@ jobs:
                   TESTRAIL_API_KEY: ${{ secrets.TESTRAIL_API_KEY }}
                   TESTRAIL_RUN_ID: ${{ steps.testrailprep.outputs.run_id }}
               run: |
-                  for file in results-*.xml; do
+                   for file in results-*.xml; do
                       echo "Handling $file"
                       trcli -y -h $TESTRAIL_URL \
                                   --project-id $TESTRAIL_PROJECT_ID \
@@ -241,8 +241,9 @@ jobs:
                                   --run-id $TESTRAIL_RUN_ID \
                                   --suite-id $TESTRAIL_SUITE_ID \
                                   --title "if you see this please check cypress build for run id not being provisioned" \
-                                  -f $file
-                  done
+                                  -f $file || true
+                      #  We want to keep uploading what we can; but don't want the failures/red marks when it fails, so we add || true above.
+                  done 
             - name: Close test run
               id: testrailpost
               if: always()
